# Generated by Django 4.2.1 on 2023-05-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
            preserve_default=False,
        ),
    ]
