# Generated by Django 4.2.1 on 2023-05-31 06:48

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=commerce.models.get_default_image, upload_to='images/'),
        ),
    ]
